name = "Tego"
license = "MIT"
homepage = "https://github.dev.global.tesco.org/Cloud/website"
tags = ["Tesco", "Documentation", "CMS", "Cloud", "CPE"]
features = []
min_version = "0.41"

[author]
  name = "Rhyan Waine"
  homepage = "https://www.linkedin.com/in/rhyanwaine/"
