name: HugotoGhpages
on: [push]
jobs:
  build:
    runs-on: testgitrunner1
    steps:
      - name: "clone"
        run: |
          rm -fr *
          git clone git@github.com:asrarparveenkp/hugoghpages.git masterCode
          git clone git@github.com:asrarparveenkp/hugoghpages.git --branch ghPages "ghPages"
          cd masterCode
          hugo
          cd ..
          cp -R masterCode/public/* ghPages/
          cd "ghPages"
          git config core.autocrlf false
          git add ./
          git commit --allow-empty -m "Automatic Documentation Build"
          git push
